# Bradsky, G., Pisarevsky, V. (2023) OpenCV, Open Computer Vision Library OpenCV version 4.9.0 https://opencv.org/ retrieved on April 18, 2024 
# Generated by Doxygen by van Heesch, D., Color Space Conversions, OpenCV, https://docs.opencv.org/4.x/d8/d01/group__imgproc__color__conversions.html, retrieved on April 18, 2024
# kpyopvision, supra56, berak (2020) error: (-215:Assertion failed) !_src.empty() in function 'cvtColor', OpenCV, https://answers.opencv.org/question/224322/error-215assertion-failed-_srcempty-in-function-cvtcolor/, retrieved April 18, 2024
# Python Software Foundation, (2024), Built-in Types, Python 3.12.3 documentation, https://docs.python.org/3/library/stdtypes.html#dict, retrieved on April 19, 2024
# Python Software Foundation (2024), Compound statements, Python 3.12.3 documentation, https://docs.python.org/3/reference/compound_stmts.html#try, retrieved April 20, 2024
# Python Software Foundation (2024), Data model, Python 3.12.3 documentation, https://docs.python.org/3/reference/datamodel.html#index-25, retrieved April 10, 2024
# Python Software Foundation, (2024), Data Structures, Python 3.12.3 documentation, https://docs.python.org/3/tutorial/datastructures.html, retrieved on April 12, 2024
# Python Software Foundation (2024), Errors and Exceptions, Python 3.12.3 documentation, https://docs.python.org/3/tutorial/errors.html, retrieved April 20, 2024
# Python Software Foundation, (2024), Python 3.12.3 documentation, Python 3.12.3 documentation, https://docs.python.org/3/, retrieved on April 10, 2024
# Python Software Foundation, (2024), The import system, Python 3.12.3 documentation, https://docs.python.org/3/reference/import.html, retrieved on April 20, 2024
# Tutorials Point OpenCV Python - Capture Video from Camera, Tutorials Point, https://www.tutorialspoint.com/opencv_python/opencv_python_capture_video_camera.htm, retrieved on April 18, 2024
# Tutorials Point OpenCV Python - Environment Setup, Tutorials Point, https://www.tutorialspoint.com/opencv_python/opencv_python_environment_setup.htm, retrieved on April 18, 2024
# Tutorials Point OpenCV Python - Extract Images from Video, Tutorials Point, https://www.tutorialspoint.com/opencv_python/opencv_python_extract_images_video.htm, retrieved on April 18, 2024
# Tutorials Point OpenCV Python - Overview, Tutorials Point, https://www.tutorialspoint.com/opencv_python/opencv_python_overview.htm, retrieved April 18 2024
# Tutorials Point OpenCV Python Tutorial, Tutorials Point, https://www.tutorialspoint.com/opencv_python/index.htm, retrieved on April 18, 2024
# Tutorials Point OpenCV Python - Reading an Image, Tutorials Point, https://www.tutorialspoint.com/opencv_python/opencv_python_reading_image.htm, retrieved on April 18 2024
# Tutorials Point OpenCV Python - Write an Image, Tutorials Point, https://www.tutorialspoint.com/opencv_python/opencv_python_write_image.htm, retrieved on April 18, 2024


# The following is a simple code snippet that takes pictures using the webcam and stores them in the same folder as "capture.png"
import cv2 as cv
def take_pic():
	cam = cv.VideoCapture(0)
	ret, frame = cam.read()
	img = cv.cvtColor(frame, cv.COLOR_RGB2RGBA)
	#cv.namedWindow('Detections', cv.WINDOW_NORMAL)
	cv.imwrite("capture.png", img)